backend:
  name: github
  repo: zarichchya/zarichchya.github.io
  branch: main
  base_url: https://decap-cms-oauth.mykola-klymyuk.workers.dev
  auth_endpoint: auth

media_folder: "imgs"
public_folder: "/imgs"

collections:
  - name: "posts_md"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "article" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Article ID", name: "article_id", widget: "number", value_type: "int" }
      - { label: "Body", name: "body", widget: "markdown" }
